version: "3"
services:
  records:
    container_name: records
    build: .
    env_file:
      - .env
    command: "./server"
    expose:
      - 5006
    ports:
      - "5006:5006"
    networks:
      - nginx_network
    restart: always

networks:
  nginx_network:
    external:
      name: nginx_default
